apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: yunikorn-configmap-reader
  namespace: abcdef
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: yunikorn-configmap-reader-binding
  namespace: abcdef
subjects:
  - kind: ServiceAccount
    name: yunikorn-admin
    namespace: abcdef
roleRef:
  kind: Role
  name: yunikorn-configmap-reader
  apiGroup: rbac.authorization.k8s.io
